version: "3"
services:
  mongodb1:
    image: mongo
    container_name: mongodb1
    restart: always
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb1:/data/db

  mongodb2:
    image: mongo
    container_name: mongodb2
    restart: always
    command: mongod --replSet rs0 --bind_ip_all --port 27018
    ports:
      - 27018:27018
    volumes:
      - ./data/mongodb2:/data/db

  mongodb3:
    image: mongo
    container_name: mongodb3
    restart: always
    command: mongod --replSet rs0 --bind_ip_all --port 27019
    ports:
      - 27019:27019
    volumes:
      - ./data/mongodb3:/data/db


networks:
  default:
    name: mongoCluster